### ISSUE TITLE
Detect common relative directory mocking mistakes under strict mode

### ISSUE THREAD

**Issue by toddr** [cpanel/Test-MockFile#59]
In our code, we had:

```perl
my $dir = '/path/to/mydir/';
Test::MockFile->dir( $dir, [] ),
-d '/path/to/mydir' or die;
```
which failed because `/path/to/mydir/` was mocked, not `/path/to/mydir`. Given a trailing slash makes no sense, I think it's reasonable to maybe die when someone tries to mock an illegal path?

**Comment by FGasper** [comment]
Either coercing or die()ing makes sense to me, IMO.

**Comment by toddr** [comment]
I'm inclined to fail with a clear message so people know they've made a mistake and their code looks right? Is that too pedantic?

**Comment by FGasper** [comment]
Either:
1) Fail w/ a clear message, or
2) Make `-d` regard `/path/to/mydir/` as interchangeable with `/path/to/mydir`.

Simplest thing probably is #1.

**Comment by toddr** [comment]
I'd prefer we clean up the object when we create the dir object.

**Comment by xsawyerx** [comment]
Different question: what's going to happen in the following case:

```
my $d1 = Test::MockFile->dir( '/dir1/../dir2/');
my $d2 = Test::MockFile->dir('dir2'/);
```

Are these equivalent?

**Comment by toddr** [comment]
> Different question: what's going to happen in the following case:
> 
> ```
> my $d1 = Test::MockFile->dir('/dir1/../dir2/');
> my $d2 = Test::MockFile->dir('/dir2/');
> ```
> 
> Are these equivalent?

What if we reject `m{/\.+/}`?

**Comment by xsawyerx** [comment]
> > Different question: what's going to happen in the following case:
> > ```
> > my $d1 = Test::MockFile->dir('/dir1/../dir2/');
> > my $d2 = Test::MockFile->dir('/dir2/');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Are these equivalent?
> 
> What if we reject `m{/\.{1,2}/}`?

That's one approach, surely, but you might need to explore `m{^/}` as well, since you can be on `/` and mock `/foo` and `foo` which will lead to the same directory. Also, the directory variable might be fed from a process that includes a lot of these `../../` in it, like a build process.

What is also interesting is the methods by which code cleans up paths like this. It is considered unsafe to try and detect `dir1/../dir2` because you can cross filesystems (symlinks, mounting points, etc.) and thus point to entirely locations.

There are two approaches for cleaning: logical and traversal. `File::Spec->canonpath()` takes the logical approach but indicates it will not collapse `x/../y` sections into `y`. However, methods like `rel2abs()`, I believe, take a mixed approach in which they try doing the traversal, but have multiple implementations - one in Pure-Perl and one written originally for BSD. I'm not even taking file system volumes (like on Windows) into account.

What we can be certain of is that traversal should not be done for two reasons: 1 People might want to mock nonexistent paths and - in cases where people want to mock directory access, `stat` calls, etc. - the traversal itself might trigger those operations.

Instead, I think the solution should be simpler and clearly documented: Paths are not cleaned up. This is the most consistent and least surprising solution long-term.

* If you mock paths `dir` and `dir/`,. you are mocking two paths.
* If you mock paths `dir//foo` and `dir/foo`, you are mocking two paths.

With that, I think we can certainly add a few checks under strict mode:
* Remove ending `/` for all paths
* Check for multiple `/` in paths
* Check for `../` or `./` in paths

(These still won't catch cases of `chdir "/"; Test::MockFile->dir("foo"); Test::MockFile->dir("/foo");` - Those can be detected with `Cwd` but you might incur a failure at a distance if some code `chdir`s to `/` as part of a build or startup process.)

**Comment by toddr** [comment]
I'm ok with the limitations mentioned. 

- Remove ending / for all paths
- Check for multiple / in paths
- Check for ../ or ./ in paths

Additionally I'm not sure we ever meant to design MockFile to work with relative paths. I'm not sure where to come down on it. Arguably the above 3 would be enough to fix the originally reported problem...

**Comment by toddr** [comment]
This is implemented via PR https://github.com/cpanel/Test-MockFile/pull/67
