### ISSUE TITLE
unlink does not work for mocked directories anymore

### ISSUE THREAD

**Issue by atoomic** [cpanel/Test-MockFile#89]
From the POD
```
unlink

Makes the virtual file go away. NOTE: This also works for directories.
```

but in real
```perl
#!perl

use Test::More;
use Test::MockFile qw{strict};

my $dir = q[/some/where];
my $mocked = Test::MockFile->dir( $dir );

mkdir( $dir );

ok -d $dir;

$mocked->unlink;
#rmdir( $dir );

ok !-d $dir;
```

output
```
╰─> perl test.pl
ok 1
not ok 2
```

**Comment by xsawyerx** [comment]
I've added a test to prove `rmdir` works. I didn't check if it was related to `Overload::FileCheck` but it works.

You shouldn't use the `->unlink()` on a directory because 1. It's a directory, 2. `->unlink()` is a method and we want to remove this interface. We want users to use the core keywords instead.
